### ISSUE TITLE
Deploying codes for webRTC

### ISSUE THREAD

**Issue by ZhuxianQuan** [WebsiteBeaver/simple-webrtc-video-chat-using-firebase#2]
I have tried to use your code in my website
script.js:51 Uncaught (in promise) TypeError: Cannot set property 'srcObject' of null
    at navigator.mediaDevices.getUserMedia.then.stream (script.js:51)
    at <anonymous>
navigator.mediaDevices.getUserMedia.then.stream @ script.js:51
Promise rejected (async)
showMyFace @ script.js:52
onload @ (index):8
script.js:23 Uncaught TypeError: Cannot set property 'srcObject' of null
    at RTCPeerConnection.pc.onaddstream.event (script.js:23)
pc.onaddstream.event @ script.js:23
(index):1 Uncaught (in promise) DOMException: Failed to set remote answer sdp: Called in wrong state: STATE_INPROGRESS
Promise (async)
readMessage @ script.js:43
(anonymous) @ EventRegistration.js:169
t.exceptionGuard @ util.js:556
e.raise @ EventQueue.js:158
e.si @ EventQueue.js:111
e.raiseEventsForChangedPath @ EventQueue.js:95
e.ee @ Repo.js:200
t.It @ PersistentConnection.js:458
t.wt @ PersistentConnection.js:452
e.wt @ Connection.js:262
e.sn @ Connection.js:256
(anonymous) @ Connection.js:157
t.xn @ WebSocketConnection.js:197
t.handleIncomingFrame @ WebSocketConnection.js:247
mySock.onmessage @ WebSocketConnection.js:144

These are issues I got from chrome browser from your source.

Please help me how to fix it.

Thank you.

**Comment by D-Marc1** [comment]
Refer to this https://github.com/WebsiteBeaver/simple-webrtc-video-chat-using-firebase/issues/1
