### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by dibolero** [WebsiteBeaver/simple-webrtc-video-chat-using-firebase#3]
I've managed to deploy the website on heroku so that I can access it through https but i still get this error. I can't see myself on the screen.
script.js:49 TypeError: Cannot set property 'srcObject' of null
    at navigator.mediaDevices.getUserMedia.then.stream (script.js:46)
    at <anonymous>

I thought this was only supposed to happen if you didn't access it using https.

**Comment by D-Marc1** [comment]
Refer to this #1.

**Comment by dibolero** [comment]
Hi! I've followed the steps by updating the repo's code, hosted it on an https server, and changed the viagenie credentials. Unfortunately I'm still facing the same problem. Here's the link to the heroku site

https://sheltered-earth-21443.herokuapp.com/index.html

**Comment by D-Marc1** [comment]
Can you try putting the all of the JS files at the bottom of your page, right before the end `</body>`?

**Comment by dmarcs** [comment]
@dibolero Take a look at [https://simple-webrtc-video-chat.firebaseapp.com/](https://simple-webrtc-video-chat.firebaseapp.com/) to see a working demo. You can use your iPhone or Android and your laptop to test it out. @D-Marc1 is correct. There's a mistake in the repo that I'm going to fix. The js needs to be placed after the HTML.

**Comment by dibolero** [comment]
Works perfectly after I transferred the JS to the bottom of the page. Thanks!
